### ISSUE TITLE
Unable to boot to Home Brew Menu when holding L button

### ISSUE THREAD

**Issue by desmond1495** [yellows8/browserhax_site#12]
I used a clean (formatted) SD card with the boot files, managed to go into Home Brew Menu and installed menuhax (stated on the screen). But when I reboot and held the L button, it didnt boot back to Home Bew Menu and nothing happened. Also, when i press back to Home Menu, the theme changes back from basic black to default theme (this happens after i installed menuhax. I followed a guide and it said not suppose to change the theme after menuhax installed.

Able to help with this issue?

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_homemenuhax/issues
