### ISSUE TITLE
10.7.0 game cards have updated dummy browser

### ISSUE THREAD

**Issue by ihaveamac** [yellows8/browserhax_site#16]
didn't know where else to leave this so...

game cards that have 10.7.0 have an updated dummy browser, which installs over the browser if updated from a 10.6.0-31 or lower system. I think this is the only time since 9.9.0 that it has been updated.

**Comment by yellows8** [comment]
Can you add that to the 3dbrew Internet_Browser page?

**Comment by ihaveamac** [comment]
https://www.3dbrew.org/w/index.php?title=Internet_Browser&type=revision&diff=18274&oldid=18199
