### ISSUE TITLE
I think the server's currently down, when will it be back up?

### ISSUE THREAD

**Issue by crimsonnight** [yellows8/browserhax_site#17]
Half way through the downgrade process so any update would be appreciated >_<

**Comment by yellows8** [comment]
Use one of the browserhax mirrors(you'll have to find one yourself).

**Comment by crimsonnight** [comment]
Thanks for the swift response, sure, how do I go about doing that though?

**Comment by yellows8** [comment]
"_find_ one yourself"

**Comment by crimsonnight** [comment]
Once I find one, how do I redirect the homebrew to check that server instead?

**Comment by yellows8** [comment]
You don't...

**Comment by crimsonnight** [comment]
Sorry! Totally my bad, thought I posted this in the ctr-httpwn section - I'm having trouble updating mtheall: https://gbatemp.net/threads/downgrading-via-a-second-3ds-steelhax-issue.447641/

**Comment by yellows8** [comment]
You can't use ctr-httpwn for NetUpdateSOAP atm.

**Comment by crimsonnight** [comment]
So currently there's no way for me to complete the system transfer? Is there an alternative to ctr-httpwn I could use? If not, do you know when the server will be back up?

**Comment by yellows8** [comment]
Without hosting the NetUpdateSOAP stuff yourself no.

**Comment by crimsonnight** [comment]
I'd be happy to do that - do you have the file/files I need? Do I just updated the 'new_url' address in line 10 of the server_config.xml to point to my server?

**Comment by yellows8** [comment]
https://github.com/yellows8/ctr-httpwn/tree/master/web "Do I just..." Yes.

EDIT: You can disable the ninupdates/http-dl stuff.

**Comment by crimsonnight** [comment]
What do you mean by disabling the ninupdates?
I'm hosting it on a friend's server and have updated line 10 for server_config.xml but it still can't download the config update for some reason, have I done something wrong? (Sorry, I'm new to this!)

**Comment by yellows8** [comment]
"What do you mean by disabling the ninupdates?" <- In the .php source ofc...

**Comment by crimsonnight** [comment]
I'm really confused - like I said, I'm not good with this stuff. I've uploaded the file you linked to a server and I've changed line 10 so that it point to it, but yet I'm unable to update the config through the ctr-httpwn app, and I'm still unable to access system transfer - what am I doing wrong?

**Comment by yellows8** [comment]
.....It sounds like you didn't even test accessing the above url in your browser......

**Comment by crimsonnight** [comment]
I did - and it looks the same as the one hosted on github?

**Comment by yellows8** [comment]
404

**Comment by crimsonnight** [comment]
https://puu.sh/s8SjG/ee4a109fc6.png

**Comment by yellows8** [comment]
"looks the same as the one hosted on github?" Server obviously needs to parse php....

**Comment by crimsonnight** [comment]
So it's incorrect at the moment?

**Comment by corizoalejandro** [comment]
Sorry, but de page is down, i try mount the page in my own server, but not works, need 3dsbrowserhax_auto.php.

PD: sorry for my bad english.

**Comment by corizoalejandro** [comment]
I get errors while loading 3dsbrowserhax_auto.php

**Comment by xFirelent** [comment]
Could someone explain me how to host the NetUpdateSOAP stuff? im newbie on this

**Comment by tsezerai** [comment]
Sorry,the ctr-httpwn server it will be online?

**Comment by yellows8** [comment]
Due to mtheall moving it will be ~2-weeks until the server is back online.

**Comment by Shinygati** [comment]
How hard would it be for an amataur like myself to host a mirror? my 3ds is still on 11.0 and i don't really want to risk updating in case something goes wrong but i had plans on doing the dsiware hack tomorrow so i'm stuck unless i either update or get ctr-httpwn working again.

**Comment by Multipixelone** [comment]
@Shinigati I did it, it was pretty simple, but that said, I do have past experience with linux. Just make sure to install apache2, and PHP, Wish I could help more, but I don't have time right now. If it's needed, I could post how to later.

**Comment by Multipixelone** [comment]
Whelp, I got it working, and I could access the URL and it WAS parsing the PHP, but it returns the error 0xd9001bf7... Sooo... @yellows8?

**Comment by Multipixelone** [comment]
Okay, I found the anwser to that! I was using the app without restarting :/

But the eShop loads permanantly... And I don't know how to fix it.

**Comment by yellows8** [comment]
Are you using .xml config which uses your NetUpdateSOAP url?

**Comment by nico403** [comment]
hi
when the servers will be up again ?
thanks

**Comment by yellows8** [comment]
https://github.com/yellows8/3ds_browserhax_common/issues/56#issuecomment-263353737
