### ISSUE TITLE
'Something failed' error when loading from HBL CIA.

### ISSUE THREAD

**Issue by bananapi761** [yellows8/browserhax_site#20]
I have Homebrew Launcher access through a CIA with A9LH/Luma and through the Sound app using soundhax. Loading through soundhax will reboot the system, and loading through the HBL CIA will give a screen saying -
00001000
01fcf000
d8e17406

something failed :(

**Comment by yellows8** [comment]
None of this has anything to do with browserhax_site. https://github.com/yellows8/hblauncher_loader/releases
