### ISSUE TITLE
yls8.mtheall.com is down

### ISSUE THREAD

**Issue by deltabeard** [yellows8/browserhax_site#7]
Browserhax cannot be run due to your website (yls8.mtheall.com) being down. It went down around 6pm - 8pm BST.

My friend is stuck on version 2 firmware because of this XD

Thank you for the great work.

**Comment by yellows8** [comment]
14:50:20 2016-07-31 -0400 <@yls8bot> Power to the *mtheall.com server was lost, the server may go offline due to power-outage soon.
14:54:00 2016-07-31 -0400 <@yls8bot> The *mtheall.com server will temporarily shutdown soon.

**Comment by deltabeard** [comment]
Thanks for the update dude. Any idea as to when it'll be back up?

**Comment by yellows8** [comment]
"power-outage" _cough_

**Comment by deltabeard** [comment]
_ahem_ An estimate could've been deduced from the last time there was a power outage on your server.

Thank you anyway.

**Comment by yellows8** [comment]
It's online now.

**Comment by Aweztube** [comment]
And now it's offline again.

**Comment by Dahrtsword** [comment]
Yes now its offline

**Comment by kurocygnus** [comment]
Offline again...

**Comment by Rurounik** [comment]
Offline here.

**Comment by corizoalejandro** [comment]
It's Offline again :'(

**Comment by Rurounik** [comment]
Still offline here

**Comment by goukifafa** [comment]
try this website guys, worked for me :) i am starting to believe YLS8 will be down for good..

http://browserhax.dahou.se/

**Comment by Rurounik** [comment]
11.1.x.xU here.
Can´t use it.
It neet to be the httpwn

**Comment by hazimthebear** [comment]
hello , down again, how can i do ? thanks a lot

**Comment by ghost** [comment]
I have a sever in a private data center that I can offer for hosting if you need a mirror. It seems that the yls8.mtheall.com server is down quite often...

**Comment by hazimthebear** [comment]
thanks a lot , i took a mirror :-)

**Comment by zediq** [comment]
is the site still down? i'm running ctr-httpwn from my 3ds and it always fail to download the  config.  is there any other option?

**Comment by yellows8** [comment]
"is the site still down?" no
