### ISSUE TITLE
How to set up and configue the site

### ISSUE THREAD

**Issue by YuriSizuku** [yellows8/browserhax_site#8]
I am eager to know how it work but I have a problem on making the site...
I try to make a web site and I can access it on my pc but it can not run on my 3ds.
I'm not sure why,  but I guess it may be a error in configuration of browserhax_cfg.php.
I have read the documents but I still don't know how to do.
Please help me,  thanks.

Here are the steps:
# http://192.168.1.144/3dsbrowserhax_auto.php

sudo apt-get git 
sudo apt-get install apache2
sudo apt-get install libapache2-mod-php5

cd /var/www/html/ #default position
git clone https://github.com/yellows8/browserhax_site.git
mv ./browserhax_site/update_browserhax.sh ./ 
./update_browserhax.sh /var/www/html/ /var/www/html/ 
cp ./3ds_browserhax_common/browserhax_cfg_example.php ./browserhax_cfg.php 
# include_once("/home/yellows8/browserhax/browserhax_cfg.php")
# include_once("browserhax_cfg.php")
# browserhax_fright.php,browserhax_fright_tx3g.php,spider31hax.php,spider28hax.php,skater31hax.php vi ./browserhax_fright.php

**Comment by yellows8** [comment]
"cp ./3ds_browserhax_common/browserhax_cfg_example.php ./browserhax_cfg.php " <- It's called 'example' for a reason.......

**Comment by YuriSizuku** [comment]
Thanks for answering me the question.
So how to make it work?
Shall I need to edit 'browserhax_cfg.php' and how to?
Another question is whether I need to compile in '3ds_browserhax_common'.

**Comment by yellows8** [comment]
See the 3ds_browserhax_common documentation.

**Comment by YuriSizuku** [comment]
Thank you very much.
I assign the value '$ropchainselect=2; $arm11code_loadfromsd=1;' in browserhaxcfg_handledefault()  and move the file arm11code.bin  that compiled by '3ds_browserhax_common/Makefile' to sd root, then  it succeed !
