### ISSUE TITLE
The site is down again

### ISSUE THREAD

**Issue by Ramian95** [yellows8/browserhax_site#9]
Hey, your site is down again
Is it like the last time?

Thanks bro

**Comment by KilimIG** [comment]
was going to open a separate issue but found this one which should suffice,

anyway; i own a few servers and am totally down for hosting a mirror of browserhax. if that interests you let me know, im always idling in the irc channel

i charge 5 dollars a week, but if you act now and sign up for a minimum of 2 weeks the price will be lowered to a WHOPPING, NEVER before seen price of 0 dollars/week

**Comment by kurx78** [comment]
Maybe if we can make an image (VMware or VirtualBox) so if the site goes down we can host the service from our home network
BTW, any news reggarding the site being down?
